apiVersion: v1
kind: Service
metadata:
  name: fsl-service
  namespace: production
  labels:
    app: fsl
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: web
  clusterIP: None
  selector:
    app: fsl
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: fsl-challenge.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fsl-service
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fsl
  namespace: production
spec:
  selector:
    matchLabels:
      app: fsl
  serviceName: fsl-service
  replicas: 3
  template:
    metadata:
      labels:
        app: fsl
    spec:
      containers:
        - name: fsl
          image: vinicpires/fsl-app:test
          ports:
            - containerPort: 80
              name: web
          # volumeMounts:
          # - name: www
          #   mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
