name: CI

defaults:
  run:
    working-directory: ./codebase/rdicidr-0.1.0

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup node js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Run tests
        run: CI=true npm run test
      - name: Build app
        run: npm run build
